networks:
  default:
     driver: bridge
     name: roboshop
     #external: true # created network already using docker network roboshopservices:
services:
  mongodb:
    image: shirisha104/mongodb:v1
    container_name: mongodb
  catalogue:
    image: shirisha104/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: shirisha104/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: shirisha104/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:  
    image: shirisha104/mysql:v1
    container_name: mysql
  shipping:
    image: shirisha104/shipping:v1
    container_name: shipping
    depends_on: 
    - mysql
    - cart
  rabbitmq: 
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123



  